[package]
name = "nanachi"
version = "0.1.0"
authors = ["nacika-ins <nacika.inscatolare@gmail.com>"]

[dependencies]
rust-sqlite = "0.3.0"
regex = "0.1.43"
rand = "0.3.17"
toml = "0.4.5"
time = "0.1.38"